export const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK';
export const CLOSE_SEARCH_MODAL = 'CLOSE_SEARCH_MODAL';
export const OPEN_SEARCH_MODAL = 'OPEN_SEARCH_MODAL';
export const REMOVE_CARD_FROM_DECK = 'REMOVE_CARD_FROM_DECK';
export const REMOVE_SEARCH_RESULT = 'REMOVE_SEARCH_RESULT';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
